#!/bin/bash

source "$HOME/.home-automation.secrets"

if [ -z $BASEDIR ]; then
        echo "ERROR: missing BASEDIR"
        exit 1
fi

FRIGATE_VERSION='0.17.1'

docker run -d \
	--name frigate \
	--privileged \
	--restart=unless-stopped \
	--stop-timeout 30 \
	--mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
	--shm-size=512m \
	-v $CAM_STORAGE_MNT/cam-storage:/media/frigate \
	-v $CAM_STORAGE_MNT/cam-config:/config \
	-v /etc/localtime:/etc/localtime:ro \
	-e FRIGATE_RTSP_PASSWORD="$FRIGATE_RTSP_PASSWORD" \
	-p 8971:8971 \
	-p 8554:8554 \
	-p 8555:8555/tcp \
	-p 8555:8555/udp \
	--device /dev/bus/usb:/dev/bus/usb \
	--device /dev/dri/renderD128:/dev/dri/renderD128 \
	ghcr.io/blakeblackshear/frigate:$FRIGATE_VERSION

